"""add artist_subscriber model

Revision ID: 19863d0a851a
Revises: e45ee07bd716
Create Date: 2025-05-13 11:49:08.040605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19863d0a851a'
down_revision: Union[str, None] = 'e45ee07bd716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_subscribers')
    # ### end Alembic commands ###
