"""add song_artists table

Revision ID: 315c500f09ae
Revises: e1ad0efc5c83
Create Date: 2025-03-27 09:33:58.503761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "315c500f09ae"
down_revision: Union[str, None] = "e1ad0efc5c83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song_artists",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "artist_id"),
    )
    op.execute("""
        INSERT INTO song_artists (song_id, artist_id)
        SELECT id, user_id FROM songs WHERE user_id IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song_artists")
    # ### end Alembic commands ###
