"""Song modified (FK not null)

Revision ID: 4d1a63beb7b2
Revises: 4c62d2683b4b
Create Date: 2024-11-28 11:08:04.252792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1a63beb7b2'
down_revision: Union[str, None] = '4c62d2683b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
