"""Friend model

Revision ID: 795284606b52
Revises: 015cff47429a
Create Date: 2024-11-30 12:45:09.971248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795284606b52'
down_revision: Union[str, None] = '015cff47429a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('pending', 'friends', 'deleted', name='friendstatus'), server_default='pending', nullable=False),
    sa.Column('user_sended_id', sa.Integer(), nullable=False),
    sa.Column('user_received_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_received_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_sended_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
