"""add track number field in Song model

Revision ID: e1ad0efc5c83
Revises: fe3e91545f94
Create Date: 2025-03-25 10:43:52.415622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ad0efc5c83'
down_revision: Union[str, None] = 'fe3e91545f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('track_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'track_number')
    # ### end Alembic commands ###
